package:
  format-version: "1.0.0"
  name: "net_apps_sam_9x7"
  version: "v3.2.0"
  type: "application"
  status: "production"
  
  dependencies:
    - name: "net"
      type: "package"
      version: "v3.12.2"
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "csp"
      type: "package"
      version: "v3.19.4"
    - name: "bsp"
      type: "package"
      version: "v3.20.1"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
